"use client";
import { useState } from "react";
type RecordRow={id:string;team_a_name:string;team_b_name:string;team_a_sets:number;team_b_sets:number;winner_name:string;played_at:string};
export default function MatchRecordManager({records}:{records:RecordRow[]}){
 const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const r=await fetch('/api/admin/match-records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({teamA:f.get('teamA'),teamB:f.get('teamB'),setsA:f.get('setsA'),setsB:f.get('setsB'),playedAt:f.get('playedAt')})});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'저장 실패');setBusy(false);return;}location.reload();}
 async function remove(id:string){if(!confirm('이 기록을 삭제할까요?'))return;await fetch(`/api/admin/match-records/${id}`,{method:'DELETE'});location.reload();}
 async function reset(){if(!confirm('정기내전 통계와 상세 기록을 전부 초기화할까요? 되돌릴 수 없습니다.'))return;setBusy(true);const r=await fetch('/api/admin/match-records/reset',{method:'DELETE'});if(r.ok)location.reload();else{const j=await r.json().catch(()=>({}));setMsg(j.error||'초기화 실패');setBusy(false);}}
 return <div className="admin-functional-page"><section className="card"><div className="dashboard-head"><div><span>STAFF ONLY</span><h1>정기내전 상세 기록</h1><p className="muted">결과 등록·삭제와 통계 초기화를 관리합니다.</p></div><button className="button danger" onClick={reset} disabled={busy}>정기내전 통계 전체 초기화</button></div><form className="record-create-grid" onSubmit={add}><input name="teamA" placeholder="A팀 이름" required/><input name="setsA" type="number" min="0" defaultValue="2" required/><input name="teamB" placeholder="B팀 이름" required/><input name="setsB" type="number" min="0" defaultValue="1" required/><input name="playedAt" type="datetime-local"/><button className="button primary" disabled={busy}>결과 저장</button></form>{msg&&<p className="form-error">{msg}</p>}</section><section className="card"><div className="dashboard-head"><div><span>RECORDS</span><h2>등록 기록 {records.length}건</h2></div></div><div className="record-admin-list">{records.map(x=><article key={x.id}><div><b>{x.team_a_name} {x.team_a_sets} : {x.team_b_sets} {x.team_b_name}</b><span>{new Date(x.played_at).toLocaleString('ko-KR')} · 우승 {x.winner_name}</span></div><button className="button danger" onClick={()=>remove(x.id)}>삭제</button></article>)}{!records.length&&<p className="empty-copy">등록된 기록이 없습니다.</p>}</div></section></div>
}
